//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace iTOLEDO.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class RealX3Entity : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new RealX3Entity object using the connection string found in the 'RealX3Entity' section of the application configuration file.
        /// </summary>
        public RealX3Entity() : base("name=RealX3Entity", "RealX3Entity")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new RealX3Entity object.
        /// </summary>
        public RealX3Entity(string connectionString) : base(connectionString, "RealX3Entity")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new RealX3Entity object.
        /// </summary>
        public RealX3Entity(EntityConnection connection) : base(connection, "RealX3Entity")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
    }

    #endregion

    
}
